### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Vanuan** [Luxoft/iviLink#8]
Any instruction on how to build ivilink for android is missing.

**Comment by promihu** [comment]
iviLink  v. 1.0.1 or earlier may be build for Ubuntu only. Android support is planned for upcoming release (in approx 2 weeks)

**Comment by Vanuan** [comment]
What android versions will it target?

**Comment by kostiakhait** [comment]
2.2 and later

**Comment by Vanuan** [comment]
I've tried to build the ivilink utils library. Here's my effort: https://github.com/ivilink/ividroid

Encountered an issue with functions for byte endianess conversion: http://code.google.com/p/android/issues/detail?id=24320

Here's a proposed patch: 2441e53cfa1f6af6f6b928aad4d6e7da010f3c37

**Comment by Vanuan** [comment]
Another issue I had to deal with is the use of STL. By default NDK doesn't provide STL library. But it can be enabled using the `APP_STL` variable: ivilink/ividroid@7df90cdef1130ba9d8412f9f8a1e01889af3ccfa

**Comment by Vanuan** [comment]
Yet another thing: `iviLink/utils/json/` uses exceptions which are not enabled by default in the Android NDK.
Here's a fix to enable it: 4ba8fe6076d50af6b1a21db0bf2d07ae789d66dc

**Comment by Vanuan** [comment]
There is more: `iviLink/utils/ipc/private/CIpc.cpp` requires `std::tr1::shared_ptr`, which is not available in the STLport.

**Comment by Vanuan** [comment]
The solution is to use the GNU libstdc++ implementation that fully supports C++ exceptions and RTTI:
ivilink/ividroid@225519b2fc1bbbfb7007423791e004a011ea6922

**Comment by Vanuan** [comment]
After yet another fix (822ed5e865da5790699bfa39b22ade7205ba2413) I was able to build the `IviLinkUtils` library for Android.
Two more libraries to go.
